# Generated by Django 3.1.3 on 2020-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
