# Generated by Django 3.1.3 on 2020-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0012_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
