# Generated by Django 3.1.3 on 2020-12-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0013_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='image_height', null=True, upload_to='pics', width_field='image_width'),
        ),
    ]
