# Generated by Django 3.1.3 on 2020-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0014_auto_20201211_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
