# Generated by Django 3.1.3 on 2020-12-15 10:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0015_item_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
